name: Build and Deploy Docs

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for tag/version

        # More info on options: https://github.com/conda-incubator/setup-miniconda
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
            python-version: 3.11
            environment-file: requirements.yaml

            channels: conda-forge,defaults

            activate-environment: docs
            auto-update-conda: false
            auto-activate-base: false
            show-channel-urls: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build Documentation
        shell: bash -l {0}
        working-directory: docs
        run: |
          make html

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _build/html
          branch: docs